
{% set name = "XRFtomo" %}
{% set version = "1.0.7" %}
{% set repo = "fabricioSMarin" %}
#tomography
#fabricioSMarin

package:
  name: {{ name|lower }} 
  version: {{ version }}

source:
  path: ../XRFtomo
  # url: https://github.com/{{ repo }}/{{ name }}/archive/v{{ version }}.tar.gz

# channels:
#   - conda-forge

build:
  skip: false # [win]
  number: 0
  entry_points:
    - xrftomo = xrftomo.__main__:main

requirements:
  host:
    - python=3.7
    - pip
  run:
    - python=3.7
    - dxchange
    - tomopy
    - dxfile
    - h5py
    - matplotlib
    - numpy
    - pandas
    - pyqtgraph
    - scipy
    - seaborn
    - setuptools
    - scikit-image
    - pywin32
    - astropy
    - pyqt
    - pywin32 [win]

test:
  source_files:
    - xrftomo/menu_installer.py
  imports:
    - xrftomo

about:
  home: https://github.com/{{ repo }}/XRFtomo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Tomography software for APS beamlines'
  description: |
    XRFtomo brings together a variety of image processing tools used for preparing, 
    processing and reconstructing 3D renditions of samples imaged using a 
    synchrotron-based x-ray fluorescence (XRF) microprobe or nanoprobe at the 
    Advanced Photon Source (APS).
  dev_url: https://github.com/{{ repo }}/XRFtomo

extra:
  recipe-maintainers:
    - FabricioSMarin